[package]
name = "encoder"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "encoder"
path = "src/main.rs"

[dependencies]
anyhow     = { workspace = true }
clap       = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
walkdir    = { workspace = true }
rand       = "0.8"
candle-core = { version = "0.8", features = [] }
candle-nn   = { version = "0.8", features = [] }

[features]
cuda = ["candle-core/cuda", "candle-nn/cuda"]
